!ocl prefetch_read(GRD_xc(iijj+block_size    ,k,l,AIJ,XDIR)  ,level=2,strong=1)
!ocl prefetch_read(GRD_xc(iijj+block_size+64 ,k,l,AIJ,XDIR)  ,level=2,strong=1)
!ocl prefetch_read(GRD_xc(iijj+block_size+128,k,l,AIJ,XDIR)  ,level=2,strong=1)
!ocl prefetch_read(GRD_xc(iijj+block_size    ,k,l,AIJ,YDIR)  ,level=2,strong=1)
!ocl prefetch_read(GRD_xc(iijj+block_size+64 ,k,l,AIJ,YDIR)  ,level=2,strong=1)
!ocl prefetch_read(GRD_xc(iijj+block_size+128,k,l,AIJ,YDIR)  ,level=2,strong=1)
!ocl prefetch_read(GRD_xc(iijj+block_size    ,k,l,AIJ,ZDIR)  ,level=2,strong=1)
!ocl prefetch_read(GRD_xc(iijj+block_size+64 ,k,l,AIJ,ZDIR)  ,level=2,strong=1)
!ocl prefetch_read(GRD_xc(iijj+block_size+128,k,l,AIJ,ZDIR)  ,level=2,strong=1)
!ocl prefetch_read(GRD_xr_ij_l(iijj+block_size    ,K0,l,AIJ,XDIR),level=2,strong=1)
!ocl prefetch_read(GRD_xr_ij_l(iijj+block_size+64 ,K0,l,AIJ,XDIR),level=2,strong=1)
!ocl prefetch_read(GRD_xr_ij_l(iijj+block_size+128,K0,l,AIJ,XDIR),level=2,strong=1)
!ocl prefetch_read(GRD_xr_ij_l(iijj+block_size    ,K0,l,AIJ,YDIR),level=2,strong=1)
!ocl prefetch_read(GRD_xr_ij_l(iijj+block_size+64 ,K0,l,AIJ,YDIR),level=2,strong=1)
!ocl prefetch_read(GRD_xr_ij_l(iijj+block_size+128,K0,l,AIJ,YDIR),level=2,strong=1)
!ocl prefetch_read(GRD_xr_ij_l(iijj+block_size    ,K0,l,AIJ,ZDIR),level=2,strong=1)
!ocl prefetch_read(GRD_xr_ij_l(iijj+block_size+64 ,K0,l,AIJ,ZDIR),level=2,strong=1)
!ocl prefetch_read(GRD_xr_ij_l(iijj+block_size+128,K0,l,AIJ,ZDIR),level=2,strong=1)
