!ocl prefetch_read(rhovz(iijj    ,k,l),level=1,strong=1)
!ocl prefetch_read(rhovz(iijj+64 ,k,l),level=1,strong=1)
!ocl prefetch_read(rhovz(iijj+128,k,l),level=1,strong=1)
!ocl prefetch_read(rhovz(iijj+192,k,l),level=1,strong=1)
!ocl prefetch_read(rhovz(iijj+256,k,l),level=1,strong=1)
