!ocl prefetch_read(GRD_xc(iijj+block_size    ,k,l,AJ ,XDIR)  ,level=2,strong=1)
!ocl prefetch_read(GRD_xc(iijj+block_size+64 ,k,l,AJ ,XDIR)  ,level=2,strong=1)
!ocl prefetch_read(GRD_xc(iijj+block_size+128,k,l,AJ ,XDIR)  ,level=2,strong=1)
!ocl prefetch_read(GRD_xc(iijj+block_size    ,k,l,AJ ,YDIR)  ,level=2,strong=1)
!ocl prefetch_read(GRD_xc(iijj+block_size+64 ,k,l,AJ ,YDIR)  ,level=2,strong=1)
!ocl prefetch_read(GRD_xc(iijj+block_size+128,k,l,AJ ,YDIR)  ,level=2,strong=1)
!ocl prefetch_read(GRD_xc(iijj+block_size    ,k,l,AJ ,ZDIR)  ,level=2,strong=1)
!ocl prefetch_read(GRD_xc(iijj+block_size+64 ,k,l,AJ ,ZDIR)  ,level=2,strong=1)
!ocl prefetch_read(GRD_xc(iijj+block_size+128,k,l,AJ ,ZDIR)  ,level=2,strong=1)
!ocl prefetch_read(GRD_xr_ij_l(iijj+block_size    ,K0,l,AJ ,XDIR),level=2,strong=1)
!ocl prefetch_read(GRD_xr_ij_l(iijj+block_size+64 ,K0,l,AJ ,XDIR),level=2,strong=1)
!ocl prefetch_read(GRD_xr_ij_l(iijj+block_size+128,K0,l,AJ ,XDIR),level=2,strong=1)
!ocl prefetch_read(GRD_xr_ij_l(iijj+block_size    ,K0,l,AJ ,YDIR),level=2,strong=1)
!ocl prefetch_read(GRD_xr_ij_l(iijj+block_size+64 ,K0,l,AJ ,YDIR),level=2,strong=1)
!ocl prefetch_read(GRD_xr_ij_l(iijj+block_size+128,K0,l,AJ ,YDIR),level=2,strong=1)
!ocl prefetch_read(GRD_xr_ij_l(iijj+block_size    ,K0,l,AJ ,ZDIR),level=2,strong=1)
!ocl prefetch_read(GRD_xr_ij_l(iijj+block_size+64 ,K0,l,AJ ,ZDIR),level=2,strong=1)
!ocl prefetch_read(GRD_xr_ij_l(iijj+block_size+128,K0,l,AJ ,ZDIR),level=2,strong=1)
