!ocl prefetch_read(rhovx(iijj+block_size    ,k,l),level=2,strong=1)
!ocl prefetch_read(rhovx(iijj+block_size+64 ,k,l),level=2,strong=1)
!ocl prefetch_read(rhovx(iijj+block_size+128,k,l),level=2,strong=1)
!ocl prefetch_read(rhovx(iijj+block_size+192,k,l),level=2,strong=1)
!ocl prefetch_read(rhovx(iijj+block_size+256,k,l),level=2,strong=1)
