!ocl prefetch_read(cinterp_HN_ij_l(iijj    ,l,AJ ,1),level=1,strong=1)
!ocl prefetch_read(cinterp_HN_ij_l(iijj+64 ,l,AJ ,1),level=1,strong=1)
!ocl prefetch_read(cinterp_HN_ij_l(iijj+128,l,AJ ,1),level=1,strong=1)
!ocl prefetch_read(cinterp_HN_ij_l(iijj    ,l,AJ ,2),level=1,strong=1)
!ocl prefetch_read(cinterp_HN_ij_l(iijj+64 ,l,AJ ,2),level=1,strong=1)
!ocl prefetch_read(cinterp_HN_ij_l(iijj+128,l,AJ ,2),level=1,strong=1)
!ocl prefetch_read(cinterp_HN_ij_l(iijj    ,l,AJ ,3),level=1,strong=1)
!ocl prefetch_read(cinterp_HN_ij_l(iijj+64 ,l,AJ ,3),level=1,strong=1)
!ocl prefetch_read(cinterp_HN_ij_l(iijj+128,l,AJ ,3),level=1,strong=1)
!ocl prefetch_write(flx_h(iijj    ,k,l,3),level=1,strong=1)
!ocl prefetch_write(flx_h(iijj+64 ,k,l,3),level=1,strong=1)
!ocl prefetch_write(flx_h(iijj+128,k,l,3),level=1,strong=1)
!ocl prefetch_write(flx_h(iijj+ADM_gall_1d    ,k,l,6),level=1,strong=1)
!ocl prefetch_write(flx_h(iijj+ADM_gall_1d+64 ,k,l,6),level=1,strong=1)
!ocl prefetch_write(flx_h(iijj+ADM_gall_1d+128,k,l,6),level=1,strong=1)
