!ocl prefetch_read(GRD_xc(iijj+block_size    ,k,l,AI ,XDIR)  ,level=2,strong=1)
!ocl prefetch_read(GRD_xc(iijj+block_size+64 ,k,l,AI ,XDIR)  ,level=2,strong=1)
!ocl prefetch_read(GRD_xc(iijj+block_size+128,k,l,AI ,XDIR)  ,level=2,strong=1)
!ocl prefetch_read(GRD_xc(iijj+block_size    ,k,l,AI ,YDIR)  ,level=2,strong=1)
!ocl prefetch_read(GRD_xc(iijj+block_size+64 ,k,l,AI ,YDIR)  ,level=2,strong=1)
!ocl prefetch_read(GRD_xc(iijj+block_size+128,k,l,AI ,YDIR)  ,level=2,strong=1)
!ocl prefetch_read(GRD_xc(iijj+block_size    ,k,l,AI ,ZDIR)  ,level=2,strong=1)
!ocl prefetch_read(GRD_xc(iijj+block_size+64 ,k,l,AI ,ZDIR)  ,level=2,strong=1)
!ocl prefetch_read(GRD_xc(iijj+block_size+128,k,l,AI ,ZDIR)  ,level=2,strong=1)
!ocl prefetch_read(GRD_xr_ij_l(iijj+block_size    ,K0,l,AI ,XDIR),level=2,strong=1)
!ocl prefetch_read(GRD_xr_ij_l(iijj+block_size+64 ,K0,l,AI ,XDIR),level=2,strong=1)
!ocl prefetch_read(GRD_xr_ij_l(iijj+block_size+128,K0,l,AI ,XDIR),level=2,strong=1)
!ocl prefetch_read(GRD_xr_ij_l(iijj+block_size    ,K0,l,AI ,YDIR),level=2,strong=1)
!ocl prefetch_read(GRD_xr_ij_l(iijj+block_size+64 ,K0,l,AI ,YDIR),level=2,strong=1)
!ocl prefetch_read(GRD_xr_ij_l(iijj+block_size+128,K0,l,AI ,YDIR),level=2,strong=1)
!ocl prefetch_read(GRD_xr_ij_l(iijj+block_size    ,K0,l,AI ,ZDIR),level=2,strong=1)
!ocl prefetch_read(GRD_xr_ij_l(iijj+block_size+64 ,K0,l,AI ,ZDIR),level=2,strong=1)
!ocl prefetch_read(GRD_xr_ij_l(iijj+block_size+128,K0,l,AI ,ZDIR),level=2,strong=1)
