!ocl prefetch_read(GRD_xc(iijj    ,k,l,AI ,XDIR)  ,level=1,strong=1)
!ocl prefetch_read(GRD_xc(iijj+64 ,k,l,AI ,XDIR)  ,level=1,strong=1)
!ocl prefetch_read(GRD_xc(iijj+128,k,l,AI ,XDIR)  ,level=1,strong=1)
!ocl prefetch_read(GRD_xc(iijj    ,k,l,AI ,YDIR)  ,level=1,strong=1)
!ocl prefetch_read(GRD_xc(iijj+64 ,k,l,AI ,YDIR)  ,level=1,strong=1)
!ocl prefetch_read(GRD_xc(iijj+128,k,l,AI ,YDIR)  ,level=1,strong=1)
!ocl prefetch_read(GRD_xc(iijj    ,k,l,AI ,ZDIR)  ,level=1,strong=1)
!ocl prefetch_read(GRD_xc(iijj+64 ,k,l,AI ,ZDIR)  ,level=1,strong=1)
!ocl prefetch_read(GRD_xc(iijj+128,k,l,AI ,ZDIR)  ,level=1,strong=1)
!ocl prefetch_read(GRD_xr_ij_l(iijj    ,K0,l,AI ,XDIR),level=1,strong=1)
!ocl prefetch_read(GRD_xr_ij_l(iijj+64 ,K0,l,AI ,XDIR),level=1,strong=1)
!ocl prefetch_read(GRD_xr_ij_l(iijj+128,K0,l,AI ,XDIR),level=1,strong=1)
!ocl prefetch_read(GRD_xr_ij_l(iijj    ,K0,l,AI ,YDIR),level=1,strong=1)
!ocl prefetch_read(GRD_xr_ij_l(iijj+64 ,K0,l,AI ,YDIR),level=1,strong=1)
!ocl prefetch_read(GRD_xr_ij_l(iijj+128,K0,l,AI ,YDIR),level=1,strong=1)
!ocl prefetch_read(GRD_xr_ij_l(iijj    ,K0,l,AI ,ZDIR),level=1,strong=1)
!ocl prefetch_read(GRD_xr_ij_l(iijj+64 ,K0,l,AI ,ZDIR),level=1,strong=1)
!ocl prefetch_read(GRD_xr_ij_l(iijj+128,K0,l,AI ,ZDIR),level=1,strong=1)
