!ocl prefetch_read(cinterp_PRA_ij(iijj    ,l),level=1,strong=1)
!ocl prefetch_read(cinterp_PRA_ij(iijj+64 ,l),level=1,strong=1)
!ocl prefetch_read(cinterp_PRA_ij(iijj+128,l),level=1,strong=1)
!ocl prefetch_read(cinterp_PRA_ij(iijj+192,l),level=1,strong=1)
!ocl prefetch_read(cinterp_PRA_ij(iijj+256,l),level=1,strong=1)
!ocl prefetch_read(cinterp_HN_ij_l(iijj    ,l,AI ,1),level=1,strong=1)
!ocl prefetch_read(cinterp_HN_ij_l(iijj+64 ,l,AI ,1),level=1,strong=1)
!ocl prefetch_read(cinterp_HN_ij_l(iijj+128,l,AI ,1),level=1,strong=1)
!ocl prefetch_read(cinterp_HN_ij_l(iijj    ,l,AI ,2),level=1,strong=1)
!ocl prefetch_read(cinterp_HN_ij_l(iijj+64 ,l,AI ,2),level=1,strong=1)
!ocl prefetch_read(cinterp_HN_ij_l(iijj+128,l,AI ,2),level=1,strong=1)
!ocl prefetch_read(cinterp_HN_ij_l(iijj    ,l,AI ,3),level=1,strong=1)
!ocl prefetch_read(cinterp_HN_ij_l(iijj+64 ,l,AI ,3),level=1,strong=1)
!ocl prefetch_read(cinterp_HN_ij_l(iijj+128,l,AI ,3),level=1,strong=1)
!ocl prefetch_write(flx_h(iijj    ,k,l,1),level=1,strong=1)
!ocl prefetch_write(flx_h(iijj+64 ,k,l,1),level=1,strong=1)
!ocl prefetch_write(flx_h(iijj+128,k,l,1),level=1,strong=1)
!ocl prefetch_write(flx_h(iijj    ,k,l,4),level=1,strong=1)
!ocl prefetch_write(flx_h(iijj+64 ,k,l,4),level=1,strong=1)
!ocl prefetch_write(flx_h(iijj+128,k,l,4),level=1,strong=1)
