!ocl prefetch_read(GMTR_T_var(iijj+block_size    ,K0,l,TI,W1),level=1,strong=1)
!ocl prefetch_read(GMTR_T_var(iijj+block_size    ,K0,l,TI,W2),level=1,strong=1)
!ocl prefetch_read(GMTR_T_var(iijj+block_size    ,K0,l,TI,W3),level=1,strong=1)
!ocl prefetch_read(GMTR_T_var(iijj+block_size    ,K0,l,TJ,W1),level=1,strong=1)
!ocl prefetch_read(GMTR_T_var(iijj+block_size    ,K0,l,TJ,W2),level=1,strong=1)
!ocl prefetch_read(GMTR_T_var(iijj+block_size    ,K0,l,TJ,W3),level=1,strong=1)
!ocl prefetch_read(GMTR_T_var(iijj+block_size+64 ,K0,l,TI,W1),level=1,strong=1)
!ocl prefetch_read(GMTR_T_var(iijj+block_size+64 ,K0,l,TI,W2),level=1,strong=1)
!ocl prefetch_read(GMTR_T_var(iijj+block_size+64 ,K0,l,TI,W3),level=1,strong=1)
!ocl prefetch_read(GMTR_T_var(iijj+block_size+64 ,K0,l,TJ,W1),level=1,strong=1)
!ocl prefetch_read(GMTR_T_var(iijj+block_size+64 ,K0,l,TJ,W2),level=1,strong=1)
!ocl prefetch_read(GMTR_T_var(iijj+block_size+64 ,K0,l,TJ,W3),level=1,strong=1)
!ocl prefetch_read(GMTR_T_var(iijj+block_size+128,K0,l,TI,W1),level=1,strong=1)
!ocl prefetch_read(GMTR_T_var(iijj+block_size+128,K0,l,TI,W2),level=1,strong=1)
!ocl prefetch_read(GMTR_T_var(iijj+block_size+128,K0,l,TI,W3),level=1,strong=1)
!ocl prefetch_read(GMTR_T_var(iijj+block_size+128,K0,l,TJ,W1),level=1,strong=1)
!ocl prefetch_read(GMTR_T_var(iijj+block_size+128,K0,l,TJ,W2),level=1,strong=1)
!ocl prefetch_read(GMTR_T_var(iijj+block_size+128,K0,l,TJ,W3),level=1,strong=1)
!ocl prefetch_read(rho  (iijj+block_size    ,k,l),level=1,strong=1)
!ocl prefetch_read(rho  (iijj+block_size+64 ,k,l),level=1,strong=1)
!ocl prefetch_read(rho  (iijj+block_size+128,k,l),level=1,strong=1)
!ocl prefetch_read(rho  (iijj+block_size+192,k,l),level=1,strong=1)
!ocl prefetch_read(rho  (iijj+block_size+256,k,l),level=1,strong=1)
