!ocl prefetch_read(cinterp_PRA_ij(iijj+block_size    ,l),level=2,strong=1)
!ocl prefetch_read(cinterp_PRA_ij(iijj+block_size+64 ,l),level=2,strong=1)
!ocl prefetch_read(cinterp_PRA_ij(iijj+block_size+128,l),level=2,strong=1)
!ocl prefetch_read(cinterp_PRA_ij(iijj+block_size+192,l),level=2,strong=1)
!ocl prefetch_read(cinterp_PRA_ij(iijj+block_size+256,l),level=2,strong=1)
!ocl prefetch_read(cinterp_HN_ij_l(iijj+block_size    ,l,AI ,1),level=2,strong=1)
!ocl prefetch_read(cinterp_HN_ij_l(iijj+block_size+64 ,l,AI ,1),level=2,strong=1)
!ocl prefetch_read(cinterp_HN_ij_l(iijj+block_size+128,l,AI ,1),level=2,strong=1)
!ocl prefetch_read(cinterp_HN_ij_l(iijj+block_size    ,l,AI ,2),level=2,strong=1)
!ocl prefetch_read(cinterp_HN_ij_l(iijj+block_size+64 ,l,AI ,2),level=2,strong=1)
!ocl prefetch_read(cinterp_HN_ij_l(iijj+block_size+128,l,AI ,2),level=2,strong=1)
!ocl prefetch_read(cinterp_HN_ij_l(iijj+block_size    ,l,AI ,3),level=2,strong=1)
!ocl prefetch_read(cinterp_HN_ij_l(iijj+block_size+64 ,l,AI ,3),level=2,strong=1)
!ocl prefetch_read(cinterp_HN_ij_l(iijj+block_size+128,l,AI ,3),level=2,strong=1)
!ocl prefetch_write(flx_h(iijj+block_size    ,k,l,1),level=2,strong=1)
!ocl prefetch_write(flx_h(iijj+block_size+64 ,k,l,1),level=2,strong=1)
!ocl prefetch_write(flx_h(iijj+block_size+128,k,l,1),level=2,strong=1)
!ocl prefetch_write(flx_h(iijj+block_size    ,k,l,4),level=2,strong=1)
!ocl prefetch_write(flx_h(iijj+block_size+64 ,k,l,4),level=2,strong=1)
!ocl prefetch_write(flx_h(iijj+block_size+128,k,l,4),level=2,strong=1)
