!ocl prefetch_read(GRD_xc(iijj    ,k,l,AIJ,XDIR)  ,level=1,strong=1)
!ocl prefetch_read(GRD_xc(iijj+64 ,k,l,AIJ,XDIR)  ,level=1,strong=1)
!ocl prefetch_read(GRD_xc(iijj+128,k,l,AIJ,XDIR)  ,level=1,strong=1)
!ocl prefetch_read(GRD_xc(iijj    ,k,l,AIJ,YDIR)  ,level=1,strong=1)
!ocl prefetch_read(GRD_xc(iijj+64 ,k,l,AIJ,YDIR)  ,level=1,strong=1)
!ocl prefetch_read(GRD_xc(iijj+128,k,l,AIJ,YDIR)  ,level=1,strong=1)
!ocl prefetch_read(GRD_xc(iijj    ,k,l,AIJ,ZDIR)  ,level=1,strong=1)
!ocl prefetch_read(GRD_xc(iijj+64 ,k,l,AIJ,ZDIR)  ,level=1,strong=1)
!ocl prefetch_read(GRD_xc(iijj+128,k,l,AIJ,ZDIR)  ,level=1,strong=1)
!ocl prefetch_read(GRD_xr_ij_l(iijj    ,K0,l,AIJ,XDIR),level=1,strong=1)
!ocl prefetch_read(GRD_xr_ij_l(iijj+64 ,K0,l,AIJ,XDIR),level=1,strong=1)
!ocl prefetch_read(GRD_xr_ij_l(iijj+128,K0,l,AIJ,XDIR),level=1,strong=1)
!ocl prefetch_read(GRD_xr_ij_l(iijj    ,K0,l,AIJ,YDIR),level=1,strong=1)
!ocl prefetch_read(GRD_xr_ij_l(iijj+64 ,K0,l,AIJ,YDIR),level=1,strong=1)
!ocl prefetch_read(GRD_xr_ij_l(iijj+128,K0,l,AIJ,YDIR),level=1,strong=1)
!ocl prefetch_read(GRD_xr_ij_l(iijj    ,K0,l,AIJ,ZDIR),level=1,strong=1)
!ocl prefetch_read(GRD_xr_ij_l(iijj+64 ,K0,l,AIJ,ZDIR),level=1,strong=1)
!ocl prefetch_read(GRD_xr_ij_l(iijj+128,K0,l,AIJ,ZDIR),level=1,strong=1)
